"""Add background_image column to Event model

Revision ID: 94325e9bcfc2
Revises: 
Create Date: 2024-11-15 23:16:37.560111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94325e9bcfc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('background_image')

    # ### end Alembic commands ###
