"""Add telephone field to User model

Revision ID: eba5da3eef90
Revises: 94325e9bcfc2
Create Date: 2024-11-20 19:38:45.679274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba5da3eef90'
down_revision = '94325e9bcfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
